### ISSUE TITLE
Por favor, modifique la pregunta

### ISSUE THREAD

**Issue by domainbf** [bastiendmt/country-rank#411]
Hay algunos errores en China en el mapa. Hong Kong, Macao y Taiwán. Esto puede ser una región, pero no puede ser un país. Pertenece a China.

**Comment by bastiendmt** [comment]
Hi @domainbf Thanks for your feedback, The data for this projet is coming from https://restcountries.com/

As I can't manage the source, I'll close this issue

More context here https://gitlab.com/restcountries/restcountries/-/issues/227
